# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: All About Otters
email: tjharris52804@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a website all about otters. It is a reliable, useful website with a lot of research and work put into it. 
  It was made to help raise awareness about otters and to help them. When you look at this website, be sure to do what
  you can to help!
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "otters.net" # the base hostname & protocol for your site
twitter_username: N/A
github_username:  MasterCheezOtter

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
